### PR TITLE
stop_mocking() should untrace all functions (closes #66, #78)

### LINKED ISSUE #66: with_mock_api() does not fully clean up (untrace)
i have a test where i use httptest like this

test_that("check list parameter", {
  httptest::with_mock_api({
    expect_error(testClient$getMatrixData(c(10)), regexp = "listOfMatrixNames needs to be a vector of strings")
    expect_error(testClient$getMatrixData(10), regexp = "listOfMatrixNames needs to be a vector of strings")
    expect_error(testClient$getMatrixData("10", 10), regexp = "repository needs to be a string")
    expect_error(testClient$getMatrixData("bla"), regexp = "POST.*")
    expect_error(testClient$getMatrixData(c("bla", "blub")), regexp = "POST.*")
  })
})

and that works fine. i have also tests where i do real http request but if they run together in the same R session the real connection tests start throwing exception like this.

 Error in readBin(con, "raw", nbytes) : invalid connection

That happens when uploading files using httr::upload_file(). i have to restart the session to make the integration tests pass again.

I include library("httptest") in setup.R (which is used by both, integration tests and mock tests)

R version: 4.1.0
Httr: 1.4.2
Httptest: 4.1.0

my crazy wild guess:
httr::POST is missing here?
https://github.com/nealrichardson/httptest/blob/5048d8e88c3bcdafdfca56b52b4dd9d8578ea195/R/trace.R#L32

### PR DESCRIPTION
**Pull request by kforner**
fixed stop_mocking() that did not untrace all functionstly called safe_untrace. Added corresponding tests. Should fix issue #78 and #66.

### CODE REVIEW

File: tests/testthat/test-mock-api.R [hunk 1]
```diff
@@ -212,6 +212,17 @@ public({
       )
     })
   })
+
+  # check that the functions are untraced
```
Comment (nealrichardson) [inline tests/testthat/test-mock-api.R:216]: Let's move these tests to test-trace.R, and to be explicit about what's being tested, let's have two versions, like: 

```
with_mock_api({
  test_that("These functions are traced", {
    expect_true(inherits(..., "functionWithTrace"))
    ...
  })
})

test_that("Now they're not traced anymore", {
  expect_false(inherits(..., "functionWithTrace"))
  ...
})
```

File: tests/testthat/test-mock-api.R [hunk 2]
```diff
@@ -212,6 +212,17 @@ public({
...
+  expect_false(inherits(httr:::body_config, "functionWithTrace"))
+  expect_false(inherits(curl::form_file, "functionWithTrace"))
+  expect_false(inherits(httr:::request_perform, "functionWithTrace"))
+  for (verb in c("GET", "PUT", "POST", "PATCH", "DELETE", "VERB", "RETRY")) {
+    fun <- getFromNamespace(verb, 'httr')
```
Comment (nealrichardson) [inline tests/testthat/test-mock-api.R:221]: So that we don't have to use `:::` to get them:

```suggestion
  for (fun_name in c("GET", "PUT", "POST", "PATCH", "DELETE", "VERB", "RETRY", "body_config", "request_perform")) {
    fun <- getFromNamespace(fun_name, "httr")
```

File: R/trace.R [hunk 3]
```diff
@@ -61,8 +61,10 @@ quietly <- function(expr) {
 #' @return Nothing; called for its side effects
 #' @export
 stop_mocking <- function() {
-  safe_untrace(curl::form_file)
-  invisible(safe_untrace("request_perform", add_headers))
+  safe_untrace("request_perform", add_headers)
```
Comment (nealrichardson) [inline R/trace.R:64]: No reason to treat these two functions differently

```suggestion
  safe_untrace("request_perform", getNamespace("httr"))
```

**Review by nealrichardson — CHANGES_REQUESTED** [review]
Thanks for doing this! A few suggestions.

File: tests/testthat/test-trace.R [hunk 4]
```diff
@@ -10,6 +10,32 @@ public({
...
+  }
+
+  with_mock_api({
+    test_that("curl/httr functions are properly traced", {
+      expect_true(all(.are_pkgs_traced()))
+    })
+  })
+
+  test_that("curl/httr functions are properly untraced", {
+      expect_true(all(!.are_pkgs_traced()))
```
Comment (nealrichardson) [inline tests/testthat/test-trace.R:36]: Same logic but I think the assertion reads more intuitively this way

```suggestion
      expect_false(any(.are_pkgs_traced()))
```

**Review by nealrichardson — APPROVED** [review]
One minor suggestion but otherwise LGTM, thank you!
